language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran

addons:
  apt:
    packages: ['gfortran','liblapack-dev']

python:
- 3.8
- 3.7
- 3.6
- 2.7

matrix:
  include:
  - os: osx
    language: minimal
    addons:
      homebrew:
        packages:
        - python3
        - gcc
        - lapack
    before_install: pip3 install pytest
    install: pip3 install -e .
  - os: windows
    language: bash
    before_install:
    - choco install miniconda3 --params="'/AddToPath:1'" --params="'/RegisterPython:1'"
    - cmd //C RefreshEnv.cmd && conda install -y pip pytest numpy
    install: 
    - cmd //C RefreshEnv.cmd && pip install -e .
    script:
    - cmd //C RefreshEnv.cmd && pytest -rsv

install: pip install -e .

script: pytest -rsv
