language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran

addons:
  apt:
    packages: ['gfortran','liblapack-dev']

python:
- 3.7
- 3.6
- 2.7

matrix:
  include:
  - os: osx
    language: minimal
    addons:
      homebrew:
        packages:
        - python3
        - gcc
        - lapack
    before_install: pip3 install pytest
    install: pip3 install -e .[tests,full]
  - os: windows
    language: bash
    env: PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:$PATH"
    before_install:
    - choco install miniconda3 openssl.light
    - conda install -y pip pytest numpy
   install: pip install -e .[tests,full,cov]

install: pip install -e .[tests,full]

script: pytest -rsv
