language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
- 3.7
- 3.6
- 2.7

matrix:
  include:
  - os: osx
    language: minimal
    addons:
      homebrew:
        packages:
        - python3
    before_install: pip3 install pytest
    install: pip3 install -e .[tests,full]
  - os: linux
    python: 3.7
    before_install: pip install numpy
  - os: linux
    python: 3.6
    before_install: pip install numpy
  - os: linux
    python: 2.7
    before_install: pip install numpy
  # - os: windows
  #   language: bash
  #   env: PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:$PATH"
  #   before_install:
  #   - choco install miniconda3 openssl.light
  #   - conda install -y pip pytest numpy matplotlib
 # - os: linux
 #   python: 3.7
 #   install: pip install -e .[tests,full,cov]
 #   script:
 #   - flake8
 #   - mypy .
 #   after_success:
 #   - pytest --cov
 #   - coveralls

install: pip install -e .[tests,full]

script: pytest -rsv
